version: "2"

services:
  web:
    restart: always
    build: ./web
    expose:
      - "5000"
    volumes:
      - ./web:/usr/src/app
    command: >
      bash -c "uwsgi --socket :5000 \
                     --chdir /usr/src/app \
                     --wsgi-file run.py \
                     --callable app \
                     --master \
                     --processes 4 \
                     --threads 2"
  
  nginx:
    restart: always
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - /www/static
      - ./nginx/sites-enabled/jd:/etc/nginx/nginx.conf
    volumes_from:
      - web
    links:
      - web:web
