web:
  restart: always
  build: ./web
  expose:
    - "5000"
  volumes:
    - ./web:/usr/src/app
  command: >
    bash -c "uwsgi --http :5000 \
                   --chdir /usr/src/app \
                   --wsgi-file run.py \
                   --callable app \
                   --master \
                   --processes 4 \
                   --threads 2"

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
