web:
  restart: always
  build: ./web
  expose:
    - "5000"
  volumes:
    - ./web:/usr/src/app
  command: /usr/local/bin/flask run --host=0.0.0.0 --port 5000 --debugger

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
